
jobs:
  - name: build-and-test
    plan:
      - in_parallel:
          - get: source-code
            trigger: false
          - get: version
            params: {pre: build}
            
      - put: version
        params: {file: version/version}
      - load_var: build_version
        file: version/version
        
      - task: build-and-test
        file: source-code/ci/build-and-test.yml       
        input_mapping:
          repo: source-code  
        params:
          MAVEN_OPTS: "-Xmx1024m"
          MAVEN_ADDITIONAL_ARGS: -DskipTests -Dpackage=war
          VERSION: ((.:build_version))
          
      - put: artifactory
        params:
          path: target
#          build_uri: "https://renodesorenterprise.jfrog.io/ui/builds"
#          build_name: "SpringSecurityAuth"
#          build_number: ((.:build_version))
#          properties: "name=SpringSecurityAuth,version=((.:build_version))"
#          source_paths: "source-code/target/SpringSecurityAuth*.war"
#          target_path: "release-candidates-local/reno-rep-local/SpringSecurityAuth/((.:build_version))/SpringSecurityAuth-((.:build_version)).war"

resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/renodesor/SpringSecurityAuth.git
      branch: main
#      private_key: {{private_key}}

  - name: artifactory
    type: artifactory
    source:
      #url: "https://renodesorenterprise.jfrog.io/artifactory"
      #username: ((artifactory-username))
      #password: ((artifactory-password))
      #repository: "maven-releases-local"
      
      api_key: da269b86-62ae-4987-92ab-a3863a400735
      host: https://renodesorenterprise.jfrog.io/artifactory
      repository_id: release-candidates-local
      group_id: com.renodesor.web
      artifact_id: SpringSecurityAuth
#      enforce_semver: true    
      
  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:renodesor/SpringSecurityAuth.git
      branch: main
      file: version
      private_key: {{private_key}}

resource_types:
  - name: artifactory
    type: registry-image
    source:
      repository: emeraldsquad/artifactory-resource
      tag: 2.0.14