
jobs:
  - name: build-and-test
    plan:
      - get: source-code
        trigger: true
      - get: version
        params: {bump: major}
      - put: version
        params: {file: version/version}
      - task: build-and-test
        file: source-code/ci/build-and-test.yml
        params:
          MAVEN_OPTS: "-Xmx1024m"       
      
      - put: artifactory
        params:
          build_uri: "https://renodesorenterprise.jfrog.io/ui/builds"
          build_name: "SpringSecurityAuth"
          build_number: "$(cat source-code/version)"
          properties: "name=SpringSecurityAuth,version=$(cat source-code/version)"
          source_paths: "source-code/target/SpringSecurityAuth*.war"
          target_path: "maven-releases-local/example-repo-local/SpringSecurityAuth/$(cat source-code/version)/SpringSecurityAuth-$(cat source-code/version).war"

resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/renodesor/SpringSecurityAuth.git
      branch: main
#      private_key: {{private_key}}

  - name: artifactory
    type: artifactory
    source:
      #url: "https://renodesorenterprise.jfrog.io/artifactory"
      #username: ((artifactory-username))
      #password: ((artifactory-password))
      #repository: "maven-releases-local"
      
      api_key: da269b86-62ae-4987-92ab-a3863a400735
      host: https://renodesorenterprise.jfrog.io/artifactory
      repository_id: reno-rep-remote
      group_id: com.renodesor.web
      artifact_id: SpringSecurityAuth
      enforce_semver: true    
      
  - name: version
    type: semver
    source:
      driver: git
      initial_version: 0.0.1
      uri: git@github.com:renodesor/SpringSecurityAuth.git
      branch: main
      file: version
      private_key: {{private_key}}

resource_types:
  - name: artifactory
    type: registry-image
    source:
      repository: emeraldsquad/artifactory-resource
      tag: 3.1.1